# Generated by Django 4.2.7 on 2023-11-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_is_active_color_is_active_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
