# Generated by Django 4.2.7 on 2023-11-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_real_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='real_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
