# Generated by Django 4.2.7 on 2023-11-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_commet_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='detail_img',
            field=models.ImageField(upload_to='detail/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_page',
            field=models.ImageField(upload_to='main/'),
        ),
    ]
