# Generated by Django 4.2.7 on 2023-11-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_detail_img_alter_blog_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='blogs', to='blog.comment'),
        ),
    ]
