# Generated by Django 4.2.7 on 2023-11-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='region',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='zip_code',
        ),
    ]
