# Generated by Django 4.2.7 on 2023-11-25 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_usermodel_address_remove_usermodel_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='country')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='state')),
                ('region', models.CharField(blank=True, max_length=200, null=True, verbose_name='region')),
                ('zip_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='zip code')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
